version: '3'
services:
  flyway:
    image: fly
    command: migrate
    network_mode: host
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    network_mode: host
volumes:
  db:
    driver: local


